### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by malgamves** [uniphyd/welcome#2]
We'd need a logo for our organisation. Anyone good at design or know someone?

**Comment by mistryvatsal** [comment]
Hey there, Can you make a well descriptive Readme file first, what this organization is intended to work on, or whats the motto of this group? So that I can get an idea to work on logo !

**Comment by malgamves** [comment]
@mistryvatsal, the description is up!:+1:  Tell us what you think about. Then you can show us what you've made!
